In [16]:
import profilelib.*
%use dataframe

In [17]:
@DataSchema
data class BenchmarkRow(
    val benchmark: String,
    val jvm: Double,
    val jvmError: Double,
    val native: Double,
    val nativeError: Double
)

fun loadAsDF(path: String): DataFrame<BenchmarkRow> {
    val jvm = loadScores(loadJson(path.replace("*", "jvm")))
    val native = loadScores(loadJson(path.replace("*", "linuxX64")))
    if (jvm.keys != native.keys) throw Exception()
    val benchmarks = jvm.keys.toList()

    fun Map<String, Double>.toNamedColumn(name: String): DataColumn<Double> = benchmarks
        .map { this[it]!! }
        .toColumn(name)

    return dataFrameOf(
        benchmarks.toColumn("benchmark"),
        jvm.mapValues { it.value.first }.toNamedColumn("jvm"),
        jvm.mapValues { it.value.second }.toNamedColumn("jvmError"),
        native.mapValues { it.value.first }.toNamedColumn("native"),
        native.mapValues { it.value.second }.toNamedColumn("nativeError"),
    ) as DataFrame<BenchmarkRow>
}

In [18]:
// Workaround for dataFrameConfig.display.decimalFormat = RendererDecimalFormat.of("%.2e")
// Confirmed by Kotlin Notebook that this doesn't and shouldn't work

fun DataFrame<*>.display() = convert { colsAtAnyDepth().colsOf<Double>() }.with { "%.2e".format(it) }

In [19]:
// f593cea Map benchmark

loadAsDF("../../benchmarks/vanilla/report-map-*.json")
    .add("ratio") { native / jvm }

benchmark,jvm,jvmError,native,nativeError,ratio
"MapBenchmark.controlB{size=""10""}",759119857.326849,2139402.725089,45320236.612710,207877.330196,0.059701
"MapBenchmark.controlB{size=""50""}",762446547.156493,18687427.474287,44668290.257533,193013.894885,0.058585
"MapBenchmark.controlB{size=""100""}",763925819.198096,34628628.802514,45450557.872337,72973.889414,0.059496
"MapBenchmark.controlB{size=""500""}",767693666.829037,29713713.731092,45286895.911187,73364.443041,0.058991
"MapBenchmark.controlB{size=""1000""}",757783143.131827,23556969.276731,44695049.715614,112422.409830,0.058981
"MapBenchmark.controlB{size=""5000""}",767072141.019164,29006489.952450,44836739.441361,381563.612162,0.058452
"MapBenchmark.controlB{size=""10000""}",748218820.942364,20046888.607717,46863722.060992,79497.341395,0.062634
"MapBenchmark.controlB{size=""50000""}",761032975.655372,11699539.865571,46695816.083055,62971.424581,0.061358
"MapBenchmark.controlB{size=""100000""}",749865409.047599,4897603.677021,46687021.726093,44141.337202,0.062261
"MapBenchmark.controlF{size=""10""}",746372402.644470,11452266.755355,45220468.578308,30572.529146,0.060587
"MapBenchmark.controlF{size=""50""}",760969524.502987,11401043.838612,45215823.667701,250388.729677,0.059419
"MapBenchmark.controlF{size=""100""}",756436675.706725,7526313.849475,45771252.131533,131357.984703,0.060509
"MapBenchmark.controlF{size=""500""}",759090393.451881,5115864.409421,45152667.178051,48869.833147,0.059483
"MapBenchmark.controlF{size=""1000""}",753351884.964016,20920001.256865,45289561.174857,119080.871122,0.060117
"MapBenchmark.controlF{size=""5000""}",757180715.546386,3129165.061090,45855316.491901,59825.222174,0.060561
"MapBenchmark.controlF{size=""10000""}",761764001.322986,20232447.785820,45490798.341939,130009.206091,0.059718
"MapBenchmark.controlF{size=""50000""}",756191833.287449,7440147.147796,46932557.855624,43475.048789,0.062064
"MapBenchmark.controlF{size=""100000""}",769621090.662845,22863516.203288,45397941.261383,405977.221086,0.058987
"MapBenchmark.getB2{size=""10""}",502756629.986074,547367.855774,19413969.188104,59182.452541,0.038615
"MapBenchmark.getB2{size=""50""}",496003174.485132,15508939.462558,19525703.131993,19896.508009,0.039366

In [20]:
// [master d719de9] Fix benchmarks for StringBuilder
loadAsDF("../../benchmarks/vanilla/report-stringbuilder-*.json")
    .add("ratio") { native / jvm }

benchmark,jvm,jvmError,native,nativeError,ratio
StringBuilderBenchmark.appendBig,2011.418537,10.703042,251.584028,2.408974,0.125078
StringBuilderBenchmark.appendMedium,1190.032920,13.736790,197.422228,1.986424,0.165896
StringBuilderBenchmark.appendSmall,191.171800,1.230805,19.300317,0.060918,0.100958

Let's do it with avgt instead.

In [21]:
fun findControlName(bmName: String): String = when (bmName.substringBefore(".")) {
    "MapBenchmark" -> bmName.takeIf { it.contains("get") }?.replace(Regex("get(.)\\d*")) { "control${it.groupValues[1]}" } ?: bmName
    "StringSubstringBenchmark" -> bmName.substringBefore("_") + "_control"
    "StringBuilderBenchmark" -> "StringBuilderBenchmark.control"
    else -> throw Exception()
}

// 491d85e Add control to StringBuilder

val df = loadAsDF("../../benchmarks/vanilla/report-avgt-*.json")
    .add("jvmControl") { df().single{ benchmark == findControlName(this@add.benchmark) }.jvm }
    .add("jvmControlError") { df().single{ benchmark == findControlName(this@add.benchmark) }.jvmError }
    .add("nativeControl") { df().single{ benchmark == findControlName(this@add.benchmark) }.native }
    .add("nativeControlError") { df().single{ benchmark == findControlName(this@add.benchmark) }.nativeError }
    .also { notebook.display(it.display()) }
    .filter { !benchmark.contains("control") }

benchmark,jvm,jvmError,native,nativeError,jvmControl,jvmControlError,nativeControl,nativeControlError
"MapBenchmark.controlB{size=""10""}",1.32e-09,1.03e-10,2.14e-08,4.65e-11,1.32e-09,1.03e-10,2.14e-08,4.65e-11
"MapBenchmark.controlB{size=""50""}",1.36e-09,5.87e-11,2.23e-08,1.03e-10,1.36e-09,5.87e-11,2.23e-08,1.03e-10
"MapBenchmark.controlB{size=""100""}",1.32e-09,5.60e-11,2.13e-08,3.25e-11,1.32e-09,5.60e-11,2.13e-08,3.25e-11
"MapBenchmark.controlB{size=""500""}",1.32e-09,2.58e-11,2.14e-08,6.66e-11,1.32e-09,2.58e-11,2.14e-08,6.66e-11
"MapBenchmark.controlB{size=""1000""}",1.37e-09,6.27e-11,2.14e-08,8.26e-11,1.37e-09,6.27e-11,2.14e-08,8.26e-11
"MapBenchmark.controlB{size=""5000""}",1.36e-09,2.94e-11,2.13e-08,6.94e-11,1.36e-09,2.94e-11,2.13e-08,6.94e-11
"MapBenchmark.controlB{size=""10000""}",1.32e-09,3.77e-11,2.24e-08,9.89e-11,1.32e-09,3.77e-11,2.24e-08,9.89e-11
"MapBenchmark.controlB{size=""50000""}",1.35e-09,7.62e-11,2.13e-08,8.92e-11,1.35e-09,7.62e-11,2.13e-08,8.92e-11
"MapBenchmark.controlB{size=""100000""}",1.35e-09,9.78e-11,2.13e-08,4.38e-11,1.35e-09,9.78e-11,2.13e-08,4.38e-11
"MapBenchmark.controlF{size=""10""}",1.35e-09,3.61e-11,2.23e-08,4.80e-11,1.35e-09,3.61e-11,2.23e-08,4.80e-11
"MapBenchmark.controlF{size=""50""}",1.31e-09,3.39e-11,2.23e-08,2.45e-11,1.31e-09,3.39e-11,2.23e-08,2.45e-11
"MapBenchmark.controlF{size=""100""}",1.35e-09,2.39e-11,2.22e-08,6.10e-12,1.35e-09,2.39e-11,2.22e-08,6.10e-12
"MapBenchmark.controlF{size=""500""}",1.35e-09,3.45e-11,2.30e-08,1.01e-10,1.35e-09,3.45e-11,2.30e-08,1.01e-10
"MapBenchmark.controlF{size=""1000""}",1.35e-09,2.87e-11,2.31e-08,6.09e-11,1.35e-09,2.87e-11,2.31e-08,6.09e-11
"MapBenchmark.controlF{size=""5000""}",1.31e-09,2.61e-11,2.23e-08,2.33e-11,1.31e-09,2.61e-11,2.23e-08,2.33e-11
"MapBenchmark.controlF{size=""10000""}",1.33e-09,8.05e-11,2.23e-08,1.98e-11,1.33e-09,8.05e-11,2.23e-08,1.98e-11
"MapBenchmark.controlF{size=""50000""}",1.31e-09,2.40e-11,2.23e-08,5.88e-11,1.31e-09,2.40e-11,2.23e-08,5.88e-11
"MapBenchmark.controlF{size=""100000""}",1.36e-09,2.50e-11,2.33e-08,4.91e-11,1.36e-09,2.50e-11,2.33e-08,4.91e-11
"MapBenchmark.getB2{size=""10""}",2.04e-09,1.27e-10,5.38e-08,9.02e-11,1.32e-09,1.03e-10,2.14e-08,4.65e-11
"MapBenchmark.getB2{size=""50""}",2.02e-09,4.66e-12,5.17e-08,9.70e-11,1.36e-09,5.87e-11,2.23e-08,1.03e-10

In [22]:
df
    .add("naiveRatio") { jvm / native }
    .add("naiveRatioError") { propagateErrorThroughRatio(jvm, jvmError, native, nativeError).let { "%.2e".format(it) } }
    .add("adjustedRatio") { (jvm - jvmControl) / (native - nativeControl) }
    .add("adjustedRatioError") { propagateErrorThroughRatio(
        jvm - jvmControl,
        propagateErrorThroughSum(jvmError, jvmControlError),
        native - nativeControl,
        propagateErrorThroughSum(nativeError, nativeControlError),
    ).let { "%.2e".format(it) }}
    .remove { cols { (it.name() in df.columns().map { it.name }) && it.name() != "benchmark" } }

benchmark,naiveRatio,naiveRatioError,adjustedRatio,adjustedRatioError
"MapBenchmark.getB2{size=""10""}",0.037988,5.53e-07,0.022219,9.14e-07
"MapBenchmark.getB2{size=""50""}",0.039065,8.67e-08,0.022520,3.65e-07
"MapBenchmark.getB2{size=""100""}",0.038950,9.40e-08,0.022856,3.37e-07
"MapBenchmark.getB2{size=""500""}",0.038737,5.78e-08,0.023347,1.66e-07
"MapBenchmark.getB2{size=""1000""}",0.040112,5.69e-07,0.024169,8.12e-07
"MapBenchmark.getB2{size=""5000""}",0.039001,4.89e-07,0.021667,6.57e-07
"MapBenchmark.getB2{size=""10000""}",0.039006,5.90e-08,0.023620,2.47e-07
"MapBenchmark.getB2{size=""50000""}",0.038368,4.81e-07,0.021769,7.51e-07
"MapBenchmark.getB2{size=""100000""}",0.039928,9.77e-08,0.023563,5.70e-07
"MapBenchmark.getB5{size=""10""}",0.039892,5.06e-07,0.024205,8.91e-07
"MapBenchmark.getB5{size=""50""}",0.039813,5.87e-07,0.023675,8.53e-07
"MapBenchmark.getB5{size=""100""}",0.040011,4.67e-07,0.024398,6.84e-07
"MapBenchmark.getB5{size=""500""}",0.038665,9.17e-07,0.022594,9.25e-07
"MapBenchmark.getB5{size=""1000""}",0.040193,7.50e-08,0.023221,3.76e-07
"MapBenchmark.getB5{size=""5000""}",0.039791,4.53e-07,0.022759,6.15e-07
"MapBenchmark.getB5{size=""10000""}",0.039553,6.86e-07,0.024987,7.58e-07
"MapBenchmark.getB5{size=""50000""}",0.037993,1.15e-07,0.021027,4.48e-07
"MapBenchmark.getB5{size=""100000""}",0.038917,5.31e-07,0.022449,8.78e-07
"MapBenchmark.getB8{size=""10""}",0.040452,5.23e-07,0.024890,9.14e-07
"MapBenchmark.getB8{size=""50""}",0.038923,5.44e-07,0.022673,7.98e-07